In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [39]:
# Chargement du fichier AER_credit_card_data.csv
df = pd.read_csv('AER_credit_card_data.csv')
# Afficher les 5 premières lignes du jeu de données
df.head()

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12
1,yes,0,33.25000,2.4200,0.005217,9.854167,no,no,3,34,1,13
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,58,1,5
3,yes,0,30.50000,2.5400,0.065214,137.869200,no,no,0,25,1,7
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5

In [40]:
# Voir le nombre de lignes et de colonnes
df.shape
df.tail(5)

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
1314,yes,0,33.58333,4.566,0.002146,7.333333,yes,no,0,94,1,19
1315,no,5,23.91667,3.192,0.000376,0.000000,no,no,3,12,1,5
1316,yes,0,40.58333,4.600,0.026513,101.298300,yes,no,2,1,1,2
1317,yes,0,32.83333,3.700,0.008999,26.996670,no,yes,0,60,1,7
1318,yes,0,48.25000,3.700,0.111619,344.157500,yes,no,2,2,1,0

In [41]:
# Voir les colonnes du jeu de données
df.columns
#TYPE COLONNE
df.dtypes

card            object
reports          int64
age            float64
income         float64
share          float64
expenditure    float64
owner           object
selfemp         object
dependents       int64
months           int64
majorcards       int64
active           int64
dtype: object

In [28]:
df.isna().sum()
# Repérer les doublons
df.duplicated().value_counts()

df.describe()

,reports,age,income,share,expenditure,dependents,months,majorcards,active
count,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000
mean,0.456406,33.213103,3.365376,0.068732,185.057071,0.993935,55.267627,0.817286,6.996967
std,1.345267,10.142783,1.693902,0.094656,272.218917,1.247745,66.271746,0.386579,6.305812
min,0.000000,0.166667,0.210000,0.000109,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,25.416670,2.243750,0.002316,4.583333,0.000000,12.000000,1.000000,2.000000
50%,0.000000,31.250000,2.900000,0.038827,101.298300,1.000000,30.000000,1.000000,6.000000
75%,0.000000,39.416670,4.000000,0.093617,249.035800,2.000000,72.000000,1.000000,11.000000
max,14.000000,83.500000,13.500000,0.906320,3099.505000,6.000000,540.000000,1.000000,46.000000

In [42]:
# Encodage des variables binaires (yes=1, no=0)
df['card'] = df['card'].map({'yes': 1, 'no': 0})
df['owner'] = df['owner'].map({'yes': 1, 'no': 0})
df['selfemp'] = df['selfemp'].map({'yes': 1, 'no': 0})

In [45]:
#df.head()
df.tail(5)

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
1314,1,0,33.58333,4.566,0.002146,7.333333,1,0,0,94,1,19
1315,0,5,23.91667,3.192,0.000376,0.000000,0,0,3,12,1,5
1316,1,0,40.58333,4.600,0.026513,101.298300,1,0,2,1,1,2
1317,1,0,32.83333,3.700,0.008999,26.996670,0,1,0,60,1,7
1318,1,0,48.25000,3.700,0.111619,344.157500,1,0,2,2,1,0

In [47]:
# ON SUPPRIME 'expenditure' ET 'share'pour éviter la fuite de données (data leakage)
X = df.drop(columns=['card', 'expenditure', 'share'])
y = df['card']
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   reports     1319 non-null   int64
 1   age         1319 non-null   float64
 2   income      1319 non-null   float64
 3   owner       1319 non-null   int64
 4   selfemp     1319 non-null   int64
 5   dependents  1319 non-null   int64
 6   months      1319 non-null   int64
 7   majorcards  1319 non-null   int64
 8   active      1319 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 92.9 KB

In [48]:
# 3. Division Train/Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
# 4. Création et entraînement du modèle Naïve Bayes
model_nb = GaussianNB()
model_nb.fit(X_train, y_train)
# 5. Prédiction sur les données de test
y_pred = model_nb.predict(X_test)
# 6. Évaluation du modèle
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.42      0.55        62
           1       0.84      0.97      0.90       202

    accuracy                           0.84       264
   macro avg       0.83      0.69      0.73       264
weighted avg       0.84      0.84      0.82       264

[[ 26  36]
 [  6 196]]
0.8409090909090909

In [50]:
import joblib
# 5. GÉNÉRATION DU FICHIER .PKL
filename = 'modele_naive_bayes_credit.pkl'
joblib.dump(model_nb, filename)

print(f"Le modèle a été sauvegardé avec succès sous le nom : {filename}")

Le modèle a été sauvegardé avec succès sous le nom : modele_naive_bayes_credit.pkl